# This file is a template, and might need editing before it works on your project.
# https://hub.docker.com/r/google/dart
image: "ghcr.io/cirruslabs/flutter:3.16.0"

variables:
  # Cache downloaded dependencies and plugins between builds.
  # To keep cache across branches add 'key: "$CI_JOB_NAME"'
  CACHE_DIR: .pub-cache/global_packages

cache:
  paths:
    - $CACHE_DIR

stages:
  - lint
  - build

lint:
  stage: lint
  before_script:
    - cd bicycure
    - flutter pub get
  script:
    - flutter analyze --no-pub --no-fatal-infos --no-fatal-warnings lib/

build:
  stage: build
  before_script:
    - cd bicycure
    - flutter pub get
  script:
    - flutter build apk --release --build-name=1.0.0 --build-number=1
